profile:
  message: Este es el perfil de testing

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_devops?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(sKcphorgN+nCEKhLKiG+jw==)
    password: ENC(+Sg36pj5niH9WiN9xJSrcA==)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

jasypt:
  encryptor:
    password: 12345
